source "https://rubygems.org"
# Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
gem "github-pages", "228", group: :jekyll_plugins
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "2.5.1"
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "0.15.1"
end

# Migth break github action
gem "webrick"